# Generated by Django 4.1.2 on 2022-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrip', models.TextField()),
                ('imdb_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('tic_no', models.IntegerField()),
            ],
        ),
    ]
