# Generated by Django 4.1.2 on 2022-12-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cineplex_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='threater',
            field=models.CharField(default='Alka Threater', max_length=100),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineplex_user.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
